// this file we put anything shared with all pages that existed in the app folder for example navigation bar must existed
// in every page we move to it
// if we make layout js in any folder whenever any file inside this folder will get all things in the layout file
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// children is considered the pages (components) inside the app folder if we delete it this will make show nothing
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* here make nav bar to move between pages and will show in all pages that inside the app folder */}
      <nav style={{width: "100%", backgroundColor: "teal", display : "flex", 
        justifyContent : "center" , alignItems: "center", gap: "20px" , padding : "10px" , fontSize: "35px"}}>
        <Link href="/">Home</Link>
        <Link href="/posts">Posts</Link>
        <Link href="/Articles">Article</Link>
      </nav>
        {children}
      </body>
    </html>
  );
}
